# Generated by Django 5.2.9 on 2026-02-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_logo_company_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'HR Admin'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20),
        ),
    ]
