# Generated by Django 5.2.9 on 2026-02-11 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_logo_company_primary_color'),
        ('payroll', '0002_payslip_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrule',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_income', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for infinity', max_digits=10, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 15.00 for 15%)', max_digits=5)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=0, help_text='Subtraction amount for this bracket (Sustruendo)', max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='core.company')),
            ],
            options={
                'ordering': ['min_income'],
            },
        ),
    ]
