# Generated by Django 5.2.9 on 2026-02-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_salaryrule_description_taxbracket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxbracket',
            name='deduction_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Auto-calculated if left blank', max_digits=10),
        ),
    ]
