# Generated by Django 5.2.9 on 2026-02-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_taxbracket_deduction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payslip',
            name='overtime_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
