# Generated by Django 5.2.9 on 2026-02-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employeedocument'),
        ('payroll', '0005_payslip_overtime_hours_payslip_overtime_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrule',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, help_text='If not global, only applies to selected employees.', related_name='salary_rules', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='salaryrule',
            name='is_global',
            field=models.BooleanField(default=True, help_text='If checked, applies to ALL employees.'),
        ),
    ]
